[providers]
python = "3.12"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python coachvirtualback/manage.py collectstatic --noinput"]

[start]
cmd = "python coachvirtualback/manage.py migrate --noinput && gunicorn coachvirtualback.wsgi:application --bind 0.0.0.0:$PORT"
